[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.40.0", features = ["full"] } 
